#!/bin/sh
########################################################################
##
## Author: Joe Colgan (joscolgan), Hongfei Xu (hongfeifly)
## Name: gene2transcript_mudskipper.sh
##
## Purpose:
## This script takes genomic aligned bam files generated by STAR,
## then, according to the reference genome assembly, transform these 
## bam files to transcriptomic bam file for realignment by Salmon.
## The final output is a bam file.  
##
########################################################################

## Take inputs from the command line:
mudskipper=./mudskipper-main/target/release/mudskipper
# software: mudskipper
data_dir=./data_dir
# dirctory storing genomic bam files generated by STAR
resorted_dir=./resorted_dir
# dirctory storing name-based sorted genomic bam files generated by mudskipper
reference_dir=./reference_dir
# dirctory storing reference genome assembly
transcriptome_bam_dir=./transcriptome_bam_dir
# dirctory storing transcriptomic bam files generated by mudskipper
reheader_dir=./reheader_dir
# dirctory storing transcriptomic reheader-bam files generated by mudskipper

### mudskipper: resorted bam file based on name
for name in $data_dir/*.bam;
do

name_2="$(echo "$name" | cut -d '/' -f 3 | cut -d '.' -f 1)"
echo "$name_2"

$mudskipper shuffle
--bam ${name}
-o $resorted_dir/${name_2}.resorted.bam

done

###
#transform genome-based bam file (resorted based on name using mudskipper) which generated by STAR alignment to transcriptomic bam file

for name in $resorted_dir/*sorted.bam;
do

name_2="$(echo "$name" | cut -d '/' -f 3 | cut -d '.' -f 1)"
echo "$name_2"

$mudskipper bulk \
--gtf $reference_dir/genome.gtf \
--alignment $resorted_dir/*sorted.bam \
--out $transcriptome_bam_dir/${name_2}.transcriptomic.bam \
--threads 10 \
-p

done

### transcriptome_combine
# Bombue terrestris transcriptome (Bter_1.0, Ensembl Metazoa) is separated in two parts: cdna and ncrna.
# We should combine them in one file and sort it in genomic order.

grep -v '#' $reference_dir/genome.gtf | awk '$3=="transcript"' | cut -f 1,4,5,9 | sed 's/\tgene_id/ gene_id/g' | sed 's/";//g' | sed 's/"/:/g' | awk -F '[ ]' '{print $1,$4,$5,$2,$3,$6.$7,$8,$9,$10,$11,$12,$13}' | sed 's/ transcript_id :/\t/g' | sed 's/ :/:/g' > transcript.bed

bedtools getfasta 
-fi $reference_dir/genome.fa 
-bed $reference_dir/transcript.bed 
-fo $reference_dir/total_transcriptome.fa 
-name 
-split


### Reheader transcriptomic bam file based on reference genome assembly
grep -v '#' $reference_dir/genome.gtf | awk '$3=="transcript"' | cut -f 4,5,9 | cut -d ";" -f 1,2 | awk '{print $6,$1,$2}' | awk '$4=$3-$2' | sed 's/ /\t/g' | sed 's/"//g' | cut -f 1,4 > new_header.txt

awk '$3="@SQ"' new_header.txt | awk '$4="SN:"' | awk '$5="LN:"' | awk '{print $3,$4,$1,$5,$2 }' | sed 's/SN: /SN:/g' | sed 's/LN: /LN:/g' | sed 's/ /\t/g' > new_header.tmp

for name in $transcriptome_bam_dir/*.transcriptomic.bam;
do

name_2="$(echo "$name" | cut -d '/' -f 3 | cut -d '.' -f 1)"
echo "$name_2"

samtools reheader new_header.sam ${name} > $reheader_dir/${name_2}.reheader.bam

done
