#!/bin/sh
########################################################################
##
## Author: Joe Colgan (joscolgan), Hongfei Xu (hongfeifly)
## Name: run_star.sh
##
## Purpose:
## This script takes pairs of compressed fastq files and performs 
## alignment against a database of transcripts using the RNA-Seq
## aligner, Salmon. The output Quantification File contained
## gene-level counts of each gene.
##
########################################################################

## Take inputs from the command line:
reheader_dir=./reheader_dir
# dirctory storing transcriptomic reheader-bam files generated by mudskipper
output_dir=./output_dir
# dirctory storing bam files generated by STAR
reference_dir=./reference_dir
# dirctory storing reference genome assembly

# run with bam file
for name in $reheader_dir/*.reheader.bam;
do

name_2="$(echo "$name" | cut -d '/' -f 3 | cut -d '.' -f 1)"
echo "$name_2"

salmon quant \
-l A \
-t $reference_dir/total_transcriptome.fa \
-a ${name} \
-o $output_dir \
--gcBias

done
