#!/bin/sh
########################################################################
##
## Author: Joe Colgan (joscolgan), Hongfei Xu (hongfeifly)
## Name: run_star.sh
##
## Purpose:
## This script takes pairs of compressed fastq files and performs 
## alignment against a database of transcripts using the RNA-Seq
## aligner, Salmon. The output Quantification File contained
## gene-level counts of each gene.
##
########################################################################

## Take inputs from the command line:
data_dir=./data_dir
# dirctory storing compressed fastq files
output_dir=./map_output_dir
# dirctory storing bam files generated by STAR
index_dir=./index_dir
# dirctory storing genomic index file generated for running Salmon

# run with fasta file
for name in ./reheader_dir/*.reheader.bam;
do

name_2="$(echo "$name" | cut -d '/' -f 3 | cut -d '.' -f 1)"
echo "$name_2"

salmon quant \
-l A \
-i $index_dir/salmon_index/salmon_index \
-1 ${name} \
-2 $data_dir/"$name_2".R2.fq.gz \
--validateMappings \
-o $output_dir \
--gcBias

done
