#####
# author: Joe Colgan (joscolgan), Hongfei Xu (hongfeifly)
# title: "**Transcriptomic analysis of spermatheca of
# _Bombus terrestris_ workers and queens**"
# output:
#   pdf_document: default
#   html_document: default
#   fig_width: 4
#   fig_height: 4
#   fontsize: 20pt
# descriptions: The data was gained from STAR output. This analysis was ran for
#   extracting different expressed genes between workers and queens in 
#   reproductive tissues, include spermatheca, vagina, and median oviduct.
#####

## Set work directory
setwd("rna_seq_analysis/spermatheca")

## Check working directory:
getwd()

library(DESeq2)
library(tidyverse)
library(pheatmap)
library(ggpubr)
library(UpSetR)
library(reshape2)
library(eulerr)
library(RColorBrewer)

## Load in our data:
## RNA_seq data comes from spermethacae from bumblebee workers and queens.
## Analysed using STAR and gene-level counts generated by HTSeq:
## Here we are following commands and steps from the following tutorial:
## http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html

## Create an object called 'directory' and we want to store the path to our data:
directory <- "data/spermatheca_star_gene_counts"

## Read in text file and store as an object:
sample_table <- read.table(file = "data/sample_information/spermatheca_sample_information_star.txt",
                           header = FALSE,
                           col.names = c("sample_name",
                                         "caste",
                                         "tissue",
                                         "stage",
                                         "condition"),
                           row.names = 1)

sample_table$sample_name <- row.names(sample_table)
sample_table$sample_name <- gsub(pattern = "ReadsPerGene.out.tab",
                                 replacement = "",
                                 sample_table$sample_name)

sample_table$file_name <- row.names(sample_table)
## Check the dimensions (dim) of your dataframe:
dim(sample_table)

## Assign 'NULL' to a column you want to remove:
sample_table$tissue <- NULL

## Check the dimensions (dim) of your dataframe:
dim(sample_table)

sample_table <- sample_table[, c(4, 5, 1:3)]

## build the DESeqDataSet
dds_star <- DESeqDataSetFromHTSeqCount(sampleTable = sample_table,
                                       directory = directory,
                                       design = ~ condition + stage + caste)

## Remove lowly expressed genes:
keep <- rowSums(counts(dds_star)) >= 10
dds_star <- dds_star[keep, ]

## Extract gene-level counts:
counts <- as.data.frame(counts(dds_star))
dim(counts)

## Remove unexpected rows
counts <- counts %>%
  subset(!rownames(counts) %in% c("N_unmapped",
                                  "N_multimapping",
                                  "N_noFeature",
                                  "N_ambiguous"))

## save raw counts
write.csv(counts, file = "results/spermatheca_raw_counts.csv")

## Create a list of genes per sample with at least five mapped reads:
new_list <- list()

for (name in colnames(counts)){
  new_name <- name
  new_list[[new_name]] <- row.names(subset(x = counts, counts[name] > 5))
}

## Plot upSet plot and save as a PDF:
pdf(file = "results/Upset plot displaying overlap in gene expression across spermatheca samples.pdf",
    height = 24,
    width = 8) # or other device

UpSetR::upset(fromList(new_list),
              nsets = 40,
              main.bar.color = "blue",
              text.scale = 1.1,
              nintersects = 30,
              order.by = "freq",
              mainbar.y.label = "Number of shared genes",
              sets.x.label = "Genes expressed")

dev.off()

# **Fig. 1.** Upset plot displaying overlap in gene expression across all samples.
# For each sample, the number of expressed genes,
# as well as the overlap with other samples, are provided.

## Across all samples, the total number of genes detected:
total_genes <- length(unique(sort(unlist(new_list))))

percentages <- list()

for (name in names(new_list)){
  percentages[[name]] <- length(unique(sort(unlist(new_list[[name]])))) / total_genes
}

## Examine percentage of expressed genes across:
## - Caste
## - Treatment
## - Stage
percentages_df <- as.data.frame(t(as.data.frame(percentages)))

summary(percentages_df)

percentages_df$caste <- sample_table[match(row.names(percentages_df),
                                           sample_table$sample_name), ]$caste

percentages_df$condition <- sample_table[match(row.names(percentages_df),
                                               sample_table$sample_name), ]$condition

percentages_df$stage <- sample_table[match(row.names(percentages_df),
                                           sample_table$sample_name), ]$stage

colnames(percentages_df)[1] <- "percentage"

(density_caste_plot <- ggplot(data = percentages_df,
                              aes(x = percentage,
                                 colour = caste)) +
  xlab(label = "Percentage of expressed genes") +
  geom_density() +
  scale_color_manual(values = c("red", "blue"),
                     labels = c("queen", "worker")) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold",
                                  size = 10)))
t.test(subset(percentages_df,
              caste == "Worker")$percentage,
       subset(percentages_df,
              caste == "Queen")$percentage)

(density_condition_plot <- ggplot(data = percentages_df,
                                  aes(x = percentage,
                                     colour = condition)) +
  xlab(label = "Percentage of expressed genes") +
  geom_density() +
  theme_bw() +
  theme(axis.title = element_text(face = "bold",
                                  size = 10)))

res.aov <- aov(percentage ~ condition,
               data = percentages_df)
summary(res.aov)

(density_stage_plot <- ggplot(data = percentages_df,
                              aes(x = percentage,
                                 colour = stage)) +
  xlab(label = "percentage of expressed genes") +
  geom_density() +
  theme_bw() +
  theme(axis.title = element_text(face = "bold",
                                  size = 10)))

res.aov <- aov(percentage ~ stage,
               data = percentages_df)
summary(res.aov)

## Generate a multi_panel plot:
pdf(file = "results/Density plots displaying percentage of genes expressed across spermatheca samples.pdf",
    height = 8,
    width = 24) # or other device

ggarrange(density_caste_plot,
          density_condition_plot,
          density_stage_plot,
          nrow = 1,
          ncol = 3,
          legend = NULL,
          align = "hv",
          labels = c("a",
                     "b",
                     "c"))

dev.off()
# **Fig. 2.** Density plots displaying percentage of genes expressed across samples



################################################################################
## Sample clustering

# To examine general similarities and differences within and between group,
# a distance matrix based on variance stabilising transformed (VST) counts was performed.

## Create a DESeq2 object:
deseq_object  <- DESeq(dds_star,
                       test = "LRT",
                       reduced = ~condition + stage)

## Transform gene-level counts using variance-stablising transformtion:
vsd <- vst(deseq_object,
           blind = FALSE)

## Update stage:
vsd$stage <- gsub(pattern = "Stage_IV",
                  replacement = "Day 8",
                  vsd$stage)

vsd$stage <- gsub(pattern = "Stage_II",
                  replacement = "Day 4",
                  vsd$stage)

vsd$stage <- gsub(pattern = "Stage_I",
                  replacement = "Day 2",
                  vsd$stage)

## Save object:
saveRDS(object = vsd,
        file = "results/vsd_spermatheca_caste.rds")

## create a matrix
sampleDists <- dist(t(assay(vsd)))
sampleDistMatrix <- as.matrix(sampleDists)

# rename the rownames and colnames
rowname <- as.data.frame(t(as.data.frame(as.list(rownames(sampleDistMatrix))))) %>%
  dplyr::mutate(V2 = paste(vsd$caste,
                           vsd$condition,
                           vsd$stage,
                           sep = "-"))

rownames(sampleDistMatrix) <- paste(rowname$V1,
                                    rowname$V2,
                                    sep = " - ")

colnames(sampleDistMatrix) <- NULL

colors <- colorRampPalette(rev(brewer.pal(9, "Blues")))(255)

# Plot heatmap
pdf(file = "results/Heatmap displaying distance matrix of genes expressed within and across spermatheca samples.pdf",
    height = 18,
    width = 24) # or other device

pheatmap(sampleDistMatrix,
         clustering_distance_rows = sampleDists,
         clustering_distance_cols = sampleDists,
         col = colors)

dev.off()
# **Fig. 3.** Heatmap displaying distance matrix of genes expressed within and across samples.


################################################################################
## Principal component analysis
# To examine further similarities in terms of expression profiles across samples, 
# a principal component analysis using VST gene values was performed.

## Create function for plotting:
plotPCA.san <- function(object,
                        first_pc = first_pca,
                        second_pc = second_pca,
                        intgroup = "condition",
                        ntop = 1000,
                        returnData = FALSE) {
  rv <- rowVars(assay(object))
  select <- order(rv, decreasing = TRUE)[seq_len(min(ntop,
                                                     length(rv)))]
  pca <- prcomp(t(assay(object)[select, ]))
  #return(pca)
  percentVar <- pca$sdev ^ 2 / sum(pca$sdev ^ 2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1,
                 paste,
                 collapse = " : "))
  }
  else {
    colData(object)[[intgroup]]
  }
  ## Select the PCAs and percentVar that you like instead of 1 and 2
  d <- data.frame(PC1 = pca$x[, first_pc],
                  PC2 = pca$x[, second_pc],
                  group = group, 
                  intgroup.df,
                  name = colData(vsd)[,1])
  if (returnData) {
    attr(d, "percentVar") <- percentVar[first_pc:second_pc]
    return(d)
  }
  ggplot(data = d,
         aes_string(x = "PC1",
                    y = "PC2",
                    color = "group")) +
    geom_point(data = d,
               aes(fill = group),
               colour = "black",
               pch = 21,
               size = 3) +
    xlab(paste0("PC", first_pc, ": ",
                round(percentVar[first_pc] * 100),
                "%")) +
    ylab(paste0("PC", second_pc, ": ",
                round(percentVar[second_pc] * 100),
                "%")) +
    #coord_fixed() +
    #geom_text_repel(size = 3) +
    theme_bw() +
    theme(axis.title = element_text(size = 12,
                                    face = "bold"),
          axis.text = element_text(size = 10,
                                   face = "plain"),
          legend.title = element_text(size = 12,
                                      face = "bold"),
          legend.text = element_text(size = 12,
                                     face = "plain"),
          legend.position = "none")
}

## Generate plot:
caste_plot_pc1_2 <- plotPCA.san(vsd,
                                first_pc = 1,
                                second_pc = 2,
                                intgroup = c("caste"))

caste_plot_pc1_2 <- caste_plot_pc1_2 +
  scale_fill_discrete(name = "Caste")

caste_plot_pc1_3 <- plotPCA.san(vsd,
                                first_pc = 1,
                                second_pc = 3,
                                intgroup = c("caste"))
caste_plot_pc1_3 <- caste_plot_pc1_3 +
  scale_fill_discrete(name = "Caste")

caste_plot_pc1_4 <- plotPCA.san(vsd,
                                first_pc = 1,
                                second_pc = 4,
                                intgroup = c("caste"))
caste_plot_pc1_4 <- caste_plot_pc1_4 +
  scale_fill_discrete(name = "Caste")

combined_caste_plot <- ggarrange(caste_plot_pc1_2,
                                 caste_plot_pc1_3,
                                 caste_plot_pc1_4,
                                 nrow = 1,
                                 ncol = 3,
                                 align = "hv",
                                 common.legend = TRUE)

# **Fig. 4.** Principal component analysis with first two principal components shown.

## Generate plot:
group_plot_pc1_2 <- plotPCA.san(vsd,
                                first_pc = 1,
                                second_pc = 2,
                                intgroup = c("condition"))
group_plot_pc1_2 <- group_plot_pc1_2 +
  scale_fill_brewer(name = "Treatment",
                    palette = "Blues")

group_plot_pc1_3 <- plotPCA.san(vsd,
                                first_pc = 1,
                                second_pc = 3,
                                intgroup = c("condition"))
group_plot_pc1_3 <- group_plot_pc1_3 +
  scale_fill_brewer(name = "Treatment",
                    palette = "Blues")

group_plot_pc1_4 <- plotPCA.san(vsd,
                                first_pc = 1,
                                second_pc = 4,
                                intgroup = c("condition"))
group_plot_pc1_4 <- group_plot_pc1_4 +
  scale_fill_brewer(name = "Treatment",
                    palette = "Blues")



combined_group_plot <- ggarrange(group_plot_pc1_2,
                                 group_plot_pc1_3,
                                 group_plot_pc1_4,
                                 nrow = 1,
                                 ncol = 3,
                                 align = "hv",
                                 common.legend = TRUE)


# **Fig. 5.** Principal component analysis with first two principal components shown.

stage_plot_pc1_2 <- plotPCA.san(vsd,
                                first_pc = 1,
                                second_pc = 2,
                                intgroup = c("stage"))
stage_plot_pc1_2 <- stage_plot_pc1_2 +
  scale_fill_manual(name = "Age",
                    values = c("black",
                               "grey",
                               "white"))

stage_plot_pc1_3 <- plotPCA.san(vsd,
                                first_pc = 1,
                                second_pc = 3,
                                intgroup = c("stage"))
stage_plot_pc1_3 <- stage_plot_pc1_3 +
  scale_fill_manual(name = "Age",
                    values = c("black",
                               "grey",
                               "white"))

stage_plot_pc1_4 <- plotPCA.san(vsd,
                                first_pc = 1,
                                second_pc = 4,
                                intgroup = c("stage"))
stage_plot_pc1_4 <- stage_plot_pc1_4 +
  scale_fill_manual(name = "Age",
                    values = c("black",
                               "grey",
                               "white"))


combined_stage_plot <- ggarrange(stage_plot_pc1_2,
                                 stage_plot_pc1_3,
                                 stage_plot_pc1_4,
                                 nrow = 1,
                                 ncol = 3,
                                 align = "hv",
                                 common.legend = TRUE)


#_**Fig. 6.** Principal component analysis with first two principal components shown.

## Generate a combined plot:
pca_combined <- ggarrange(combined_caste_plot,
                          combined_group_plot,
                          combined_stage_plot,
                          nrow = 3,
                          ncol = 1,
                          labels = c("a",
                                     "b",
                                     "c"),
                          align = "hv")

## Print to console:
(pca_combined)

## Save to file:
ggsave(filename = "results/spermatheca_full_pca_plot.pdf",
       height = 8,
       width = 8)


################################################################################
## Analysis of differential expressed gene between castes

## Check names of comparisons:
resultsNames(deseq_object)

## Extract results:
res <- results(deseq_object)

## Plot distribution of adjusted p values:
pdf(file = "results/Histogram of adjiusted p values for spermatheca DEG between castes.pdf",
    height = 8,
    width = 8)

hist(res$padj[res$baseMean > 1],
     breaks = 0:20 / 20,
     col = "grey50",
     border = "white",
     main = "Histogram of adjusted p-values for differentially expressed genes",
     xlab = "Adjusted p value")

dev.off()

# **Fig. 7** Histogram of adjiusted p values for DEG between castes.

## Extract results:
deseq_object_results <- results(deseq_object,
                                name = "caste_Worker_vs_Queen")

## Extract significant phenotype genes:
deseq_object_results$absL2FC <- abs(deseq_object_results$log2FoldChange)

deseq_object_results_sig <- subset(x = deseq_object_results,
                                   padj < 0.05 &
                                     absL2FC >= 1)
nrow(deseq_object_results_sig)

## Convert DESeq2 result object to a dataframe:
deseq_object_results <- as.data.frame(deseq_object_results)

deseq_object_results_sig <- as.data.frame(deseq_object_results_sig)

## Save results of gene expression between castes
write.csv(deseq_object_results_sig, file = "results/spermatheca_DEG_between_castes.csv")
write.csv(deseq_object_results, file = "results/spermatheca_gene_between_castes.csv")

## Subset genes with evidence of significantly differential expression:
deseq_object_worker_bias <- subset(x = deseq_object_results,
                                   padj < 0.05 &
                                     log2FoldChange >= 1)
nrow(deseq_object_worker_bias)

## Subset genes with evidence of significantly differential expression:
deseq_object_queen_bias <- subset(x = deseq_object_results,
                                  padj < 0.05 &
                                    log2FoldChange <= -1)
nrow(deseq_object_queen_bias)

## Plot volcano plot of:
## a) Log2FoldChange (gene expression) against:
## b) -log10 transformed p-value (significant threshold)
volcano_plot <- ggplot(deseq_object_results,
                       aes(x = log2FoldChange,
                           y = -log10(padj))) +
  xlim(-10, 10) +
  geom_point(alpha = 0.5) +
  geom_point(data = subset(as.data.frame(deseq_object_worker_bias),
                           log2FoldChange >= 1 &
                             padj < 0.05),
             aes(colour = "orange")) +
  geom_point(data = subset(as.data.frame(deseq_object_queen_bias),
                           log2FoldChange <= -1 &
                             padj < 0.05),
             aes(colour = "blue")) +
  geom_vline(xintercept = c(-1, 1),
             linetype = "dashed") +
  theme_bw() +
  theme(
    axis.title = element_text(face = "bold",
                              size = 12),
    legend.title = element_text(face = "bold",
                                size = 12),
    legend.text = element_text(face = "plain",
                               size = 12),
    legend.position = "top") +
  scale_colour_manual(values = c("blue",
                                 "orange"),
                      labels = c("Queen_biased",
                                 "Worker-biased"),
                      name = "Status")

ggsave("results/Volcano plots displaying differences in spermatheca gene expression across castes.pdf",
       plot = volcano_plot,
       width = 12,
       height = 8)

#_**Fig. 8.** Volcano plots displaying differences in gene expression



################################################################################
## Euler plot

## Extract genes found in both comparisons:
comp_counts <- as.data.frame(table(c(rownames(deseq_object_worker_bias),
                                     rownames(deseq_object_queen_bias))))

## Subset:
comp_counts_conserved <- subset(comp_counts,
                                Freq == 2)

## Compare overlap of differentially expressed genes:
venneu_caste_comparison <- euler(combinations = list("Worker DEGs" = row.names(deseq_object_worker_bias),
                                                     "Queen DEGs" = row.names(deseq_object_queen_bias)))

## Generate plot:
(caste_comparison_plot <- plot(venneu_caste_comparison,
                               quantities = TRUE,
                               edges = TRUE,
                               labels = list(fontsize = 12)))

# **Fig. 9.** Euler plot of differentially expressed genes between castes.

lintr::lint("deseq2_analysis_star_spermatheca.R")
